services:
  app:
    build: .
    ports:
      - "3000:3000"  # Expose app to the host on port 3000
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Shared volume for SSL certificates
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Shared volume for Nginx configuration
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Shared volume for SSL certificates
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Shared volume for Nginx configuration
    depends_on:
      - app  # Ensure Nginx waits for the app to be available
    restart: always