services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - homepage-network
    expose:
      - "3000"  # Expose 3000 for internal communication with NGINX
  
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Mount SSL certificates
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextjs-app
    networks:
      - homepage-network

networks:
  homepage-network:
    driver: bridge