services:
  nextjs-app:
    build:
      context: .
    ports:
      - "3000:3000"  # Map container port 3000 to localhost port 3000
    volumes:
      - .:/app        # Mount local code directory to container for live-reload
    environment:
      - NODE_ENV=development
    command: npm run dev  # Runs Next.js in development mode
    networks:
      - nextjs-net

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Map the nginx configuration file
    ports:
      - "80:80"  # Expose port 80 for HTTP
    networks:
      - nextjs-net

networks:
  nextjs-net:
    driver: bridge